number = input("input a number: ")
print ("that number is: ", number)
print(type(number))
print("lets convert this into an int and add 1 just for this line: ", (int(number) + 1))
print("now lets turn it into an int for the rest of the file")
number = (int(number))
print(type(number))
number = int(input("enter another number: "))
print("lets add 1 to that number: ", number + 1)
print(type(number))
